name: openfold_venv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - setuptools=59.5.0
  - pip
  - openmm=7.7
  - pdbfixer
  - cudatoolkit==11.3.*
  - pytorch=1.12.*
  - pytorch-lightning==1.5.10
  - biopython==1.79
  - numpy==1.21
  - PyYAML==5.4.1
  - requests
  - scipy==1.7
  - tqdm==4.62.2
  - typing-extensions==3.10
  - wandb==0.12.21
  - modelcif==0.7
  - awscli
  - bioconda::aria2
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pip:
      - deepspeed==0.5.10  # can this be updated?
      - dm-tree==0.1.6  # 0.1.6 yanked from conda-forge - update?
      - ml-collections==0.1.0  # 0.1.1 is oldest available on conda-forge - update?
      - git+https://github.com/NVIDIA/dllogger.git
      - git+https://github.com/Dao-AILab/flash-attention.git@5b838a8
